// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

#include "simple.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace petnet {
namespace simple {
namespace v1 {

inline constexpr ServerSimpleSendRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerSimpleSendRequest::ServerSimpleSendRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServerSimpleSendRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerSimpleSendRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerSimpleSendRequestDefaultTypeInternal() {}
  union {
    ServerSimpleSendRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerSimpleSendRequestDefaultTypeInternal _ServerSimpleSendRequest_default_instance_;

inline constexpr Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        error_code_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Response::Response(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseDefaultTypeInternal() {}
  union {
    Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal _Response_default_instance_;

inline constexpr ClientSimpleSendRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        receiver_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientSimpleSendRequest::ClientSimpleSendRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClientSimpleSendRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientSimpleSendRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientSimpleSendRequestDefaultTypeInternal() {}
  union {
    ClientSimpleSendRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientSimpleSendRequestDefaultTypeInternal _ClientSimpleSendRequest_default_instance_;

inline constexpr ClientSimpleRecvRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClientSimpleRecvRequest::ClientSimpleRecvRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClientSimpleRecvRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientSimpleRecvRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientSimpleRecvRequestDefaultTypeInternal() {}
  union {
    ClientSimpleRecvRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientSimpleRecvRequestDefaultTypeInternal _ClientSimpleRecvRequest_default_instance_;
}  // namespace v1
}  // namespace simple
}  // namespace petnet
static ::_pb::Metadata file_level_metadata_simple_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_simple_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_simple_2eproto = nullptr;
const ::uint32_t TableStruct_simple_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleSendRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleSendRequest, _impl_.message_id_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleSendRequest, _impl_.receiver_id_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleSendRequest, _impl_.payload_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleRecvRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ClientSimpleRecvRequest, _impl_.message_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ServerSimpleSendRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ServerSimpleSendRequest, _impl_.message_id_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::ServerSimpleSendRequest, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _impl_.error_code_),
    PROTOBUF_FIELD_OFFSET(::petnet::simple::v1::Response, _impl_.error_msg_),
    ~0u,
    0,
    2,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::petnet::simple::v1::ClientSimpleSendRequest)},
        {11, -1, -1, sizeof(::petnet::simple::v1::ClientSimpleRecvRequest)},
        {20, -1, -1, sizeof(::petnet::simple::v1::ServerSimpleSendRequest)},
        {30, 42, -1, sizeof(::petnet::simple::v1::Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::petnet::simple::v1::_ClientSimpleSendRequest_default_instance_._instance,
    &::petnet::simple::v1::_ClientSimpleRecvRequest_default_instance_._instance,
    &::petnet::simple::v1::_ServerSimpleSendRequest_default_instance_._instance,
    &::petnet::simple::v1::_Response_default_instance_._instance,
};
const char descriptor_table_protodef_simple_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014simple.proto\022\020petnet.simple.v1\"S\n\027Clie"
    "ntSimpleSendRequest\022\022\n\nmessage_id\030\001 \001(\t\022"
    "\023\n\013receiver_id\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014\"-\n"
    "\027ClientSimpleRecvRequest\022\022\n\nmessage_id\030\001"
    " \001(\t\">\n\027ServerSimpleSendRequest\022\022\n\nmessa"
    "ge_id\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\"\213\001\n\010Respons"
    "e\022\017\n\007success\030\001 \001(\010\022\024\n\007payload\030\002 \001(\014H\000\210\001\001"
    "\022\027\n\nerror_code\030\003 \001(\005H\001\210\001\001\022\026\n\terror_msg\030\004"
    " \001(\tH\002\210\001\001B\n\n\010_payloadB\r\n\013_error_codeB\014\n\n"
    "_error_msg2\246\002\n\023SimpleRequestServer\022Y\n\020Cl"
    "ientSimpleSend\022).petnet.simple.v1.Client"
    "SimpleSendRequest\032\032.petnet.simple.v1.Res"
    "ponse\022Y\n\020ClientSimpleRecv\022).petnet.simpl"
    "e.v1.ClientSimpleRecvRequest\032\032.petnet.si"
    "mple.v1.Response\022Y\n\020ServerSimpleSend\022).p"
    "etnet.simple.v1.ServerSimpleSendRequest\032"
    "\032.petnet.simple.v1.Responseb\006proto3"
};
static ::absl::once_flag descriptor_table_simple_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_simple_2eproto = {
    false,
    false,
    675,
    descriptor_table_protodef_simple_2eproto,
    "simple.proto",
    &descriptor_table_simple_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_simple_2eproto::offsets,
    file_level_metadata_simple_2eproto,
    file_level_enum_descriptors_simple_2eproto,
    file_level_service_descriptors_simple_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_simple_2eproto_getter() {
  return &descriptor_table_simple_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_simple_2eproto(&descriptor_table_simple_2eproto);
namespace petnet {
namespace simple {
namespace v1 {
// ===================================================================

class ClientSimpleSendRequest::_Internal {
 public:
};

ClientSimpleSendRequest::ClientSimpleSendRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:petnet.simple.v1.ClientSimpleSendRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientSimpleSendRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_id_(arena, from.message_id_),
        receiver_id_(arena, from.receiver_id_),
        payload_(arena, from.payload_),
        _cached_size_{0} {}

ClientSimpleSendRequest::ClientSimpleSendRequest(
    ::google::protobuf::Arena* arena,
    const ClientSimpleSendRequest& from)
    : ::google::protobuf::Message(arena) {
  ClientSimpleSendRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:petnet.simple.v1.ClientSimpleSendRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientSimpleSendRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_id_(arena),
        receiver_id_(arena),
        payload_(arena),
        _cached_size_{0} {}

inline void ClientSimpleSendRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClientSimpleSendRequest::~ClientSimpleSendRequest() {
  // @@protoc_insertion_point(destructor:petnet.simple.v1.ClientSimpleSendRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClientSimpleSendRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_id_.Destroy();
  _impl_.receiver_id_.Destroy();
  _impl_.payload_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClientSimpleSendRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:petnet.simple.v1.ClientSimpleSendRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_id_.ClearToEmpty();
  _impl_.receiver_id_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClientSimpleSendRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 70, 2> ClientSimpleSendRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClientSimpleSendRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string message_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.message_id_)}},
    // string receiver_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.receiver_id_)}},
    // bytes payload = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.payload_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message_id = 1;
    {PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.message_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string receiver_id = 2;
    {PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.receiver_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes payload = 3;
    {PROTOBUF_FIELD_OFFSET(ClientSimpleSendRequest, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\50\12\13\0\0\0\0\0"
    "petnet.simple.v1.ClientSimpleSendRequest"
    "message_id"
    "receiver_id"
  }},
};

::uint8_t* ClientSimpleSendRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:petnet.simple.v1.ClientSimpleSendRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    const std::string& _s = this->_internal_message_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "petnet.simple.v1.ClientSimpleSendRequest.message_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string receiver_id = 2;
  if (!this->_internal_receiver_id().empty()) {
    const std::string& _s = this->_internal_receiver_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "petnet.simple.v1.ClientSimpleSendRequest.receiver_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // bytes payload = 3;
  if (!this->_internal_payload().empty()) {
    const std::string& _s = this->_internal_payload();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:petnet.simple.v1.ClientSimpleSendRequest)
  return target;
}

::size_t ClientSimpleSendRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:petnet.simple.v1.ClientSimpleSendRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message_id());
  }

  // string receiver_id = 2;
  if (!this->_internal_receiver_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_receiver_id());
  }

  // bytes payload = 3;
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_payload());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClientSimpleSendRequest::_class_data_ = {
    ClientSimpleSendRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClientSimpleSendRequest::GetClassData() const {
  return &_class_data_;
}

void ClientSimpleSendRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClientSimpleSendRequest*>(&to_msg);
  auto& from = static_cast<const ClientSimpleSendRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:petnet.simple.v1.ClientSimpleSendRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_id().empty()) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  if (!from._internal_receiver_id().empty()) {
    _this->_internal_set_receiver_id(from._internal_receiver_id());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientSimpleSendRequest::CopyFrom(const ClientSimpleSendRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:petnet.simple.v1.ClientSimpleSendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClientSimpleSendRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClientSimpleSendRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClientSimpleSendRequest::InternalSwap(ClientSimpleSendRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_id_, &other->_impl_.message_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.receiver_id_, &other->_impl_.receiver_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
}

::google::protobuf::Metadata ClientSimpleSendRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simple_2eproto_getter, &descriptor_table_simple_2eproto_once,
      file_level_metadata_simple_2eproto[0]);
}
// ===================================================================

class ClientSimpleRecvRequest::_Internal {
 public:
};

ClientSimpleRecvRequest::ClientSimpleRecvRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:petnet.simple.v1.ClientSimpleRecvRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientSimpleRecvRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_id_(arena, from.message_id_),
        _cached_size_{0} {}

ClientSimpleRecvRequest::ClientSimpleRecvRequest(
    ::google::protobuf::Arena* arena,
    const ClientSimpleRecvRequest& from)
    : ::google::protobuf::Message(arena) {
  ClientSimpleRecvRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:petnet.simple.v1.ClientSimpleRecvRequest)
}
inline PROTOBUF_NDEBUG_INLINE ClientSimpleRecvRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_id_(arena),
        _cached_size_{0} {}

inline void ClientSimpleRecvRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClientSimpleRecvRequest::~ClientSimpleRecvRequest() {
  // @@protoc_insertion_point(destructor:petnet.simple.v1.ClientSimpleRecvRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClientSimpleRecvRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClientSimpleRecvRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:petnet.simple.v1.ClientSimpleRecvRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClientSimpleRecvRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 59, 2> ClientSimpleRecvRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClientSimpleRecvRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClientSimpleRecvRequest, _impl_.message_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message_id = 1;
    {PROTOBUF_FIELD_OFFSET(ClientSimpleRecvRequest, _impl_.message_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\50\12\0\0\0\0\0\0"
    "petnet.simple.v1.ClientSimpleRecvRequest"
    "message_id"
  }},
};

::uint8_t* ClientSimpleRecvRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:petnet.simple.v1.ClientSimpleRecvRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    const std::string& _s = this->_internal_message_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "petnet.simple.v1.ClientSimpleRecvRequest.message_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:petnet.simple.v1.ClientSimpleRecvRequest)
  return target;
}

::size_t ClientSimpleRecvRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:petnet.simple.v1.ClientSimpleRecvRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClientSimpleRecvRequest::_class_data_ = {
    ClientSimpleRecvRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClientSimpleRecvRequest::GetClassData() const {
  return &_class_data_;
}

void ClientSimpleRecvRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClientSimpleRecvRequest*>(&to_msg);
  auto& from = static_cast<const ClientSimpleRecvRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:petnet.simple.v1.ClientSimpleRecvRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_id().empty()) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClientSimpleRecvRequest::CopyFrom(const ClientSimpleRecvRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:petnet.simple.v1.ClientSimpleRecvRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClientSimpleRecvRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClientSimpleRecvRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClientSimpleRecvRequest::InternalSwap(ClientSimpleRecvRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_id_, &other->_impl_.message_id_, arena);
}

::google::protobuf::Metadata ClientSimpleRecvRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simple_2eproto_getter, &descriptor_table_simple_2eproto_once,
      file_level_metadata_simple_2eproto[1]);
}
// ===================================================================

class ServerSimpleSendRequest::_Internal {
 public:
};

ServerSimpleSendRequest::ServerSimpleSendRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:petnet.simple.v1.ServerSimpleSendRequest)
}
inline PROTOBUF_NDEBUG_INLINE ServerSimpleSendRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_id_(arena, from.message_id_),
        payload_(arena, from.payload_),
        _cached_size_{0} {}

ServerSimpleSendRequest::ServerSimpleSendRequest(
    ::google::protobuf::Arena* arena,
    const ServerSimpleSendRequest& from)
    : ::google::protobuf::Message(arena) {
  ServerSimpleSendRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:petnet.simple.v1.ServerSimpleSendRequest)
}
inline PROTOBUF_NDEBUG_INLINE ServerSimpleSendRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_id_(arena),
        payload_(arena),
        _cached_size_{0} {}

inline void ServerSimpleSendRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ServerSimpleSendRequest::~ServerSimpleSendRequest() {
  // @@protoc_insertion_point(destructor:petnet.simple.v1.ServerSimpleSendRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServerSimpleSendRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_id_.Destroy();
  _impl_.payload_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServerSimpleSendRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:petnet.simple.v1.ServerSimpleSendRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_id_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServerSimpleSendRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 59, 2> ServerSimpleSendRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ServerSimpleSendRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ServerSimpleSendRequest, _impl_.payload_)}},
    // string message_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ServerSimpleSendRequest, _impl_.message_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message_id = 1;
    {PROTOBUF_FIELD_OFFSET(ServerSimpleSendRequest, _impl_.message_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(ServerSimpleSendRequest, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\50\12\0\0\0\0\0\0"
    "petnet.simple.v1.ServerSimpleSendRequest"
    "message_id"
  }},
};

::uint8_t* ServerSimpleSendRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:petnet.simple.v1.ServerSimpleSendRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    const std::string& _s = this->_internal_message_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "petnet.simple.v1.ServerSimpleSendRequest.message_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    const std::string& _s = this->_internal_payload();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:petnet.simple.v1.ServerSimpleSendRequest)
  return target;
}

::size_t ServerSimpleSendRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:petnet.simple.v1.ServerSimpleSendRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message_id());
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_payload());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServerSimpleSendRequest::_class_data_ = {
    ServerSimpleSendRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServerSimpleSendRequest::GetClassData() const {
  return &_class_data_;
}

void ServerSimpleSendRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServerSimpleSendRequest*>(&to_msg);
  auto& from = static_cast<const ServerSimpleSendRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:petnet.simple.v1.ServerSimpleSendRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_id().empty()) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerSimpleSendRequest::CopyFrom(const ServerSimpleSendRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:petnet.simple.v1.ServerSimpleSendRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServerSimpleSendRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServerSimpleSendRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServerSimpleSendRequest::InternalSwap(ServerSimpleSendRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_id_, &other->_impl_.message_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
}

::google::protobuf::Metadata ServerSimpleSendRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simple_2eproto_getter, &descriptor_table_simple_2eproto_once,
      file_level_metadata_simple_2eproto[2]);
}
// ===================================================================

class Response::_Internal {
 public:
  using HasBits = decltype(std::declval<Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Response, _impl_._has_bits_);
  static void set_has_payload(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_error_code(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_error_msg(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

Response::Response(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:petnet.simple.v1.Response)
}
inline PROTOBUF_NDEBUG_INLINE Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_),
        error_msg_(arena, from.error_msg_) {}

Response::Response(
    ::google::protobuf::Arena* arena,
    const Response& from)
    : ::google::protobuf::Message(arena) {
  Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, success_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, success_),
           offsetof(Impl_, error_code_) -
               offsetof(Impl_, success_) +
               sizeof(Impl_::error_code_));

  // @@protoc_insertion_point(copy_constructor:petnet.simple.v1.Response)
}
inline PROTOBUF_NDEBUG_INLINE Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        payload_(arena),
        error_msg_(arena) {}

inline void Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, success_),
           0,
           offsetof(Impl_, error_code_) -
               offsetof(Impl_, success_) +
               sizeof(Impl_::error_code_));
}
Response::~Response() {
  // @@protoc_insertion_point(destructor:petnet.simple.v1.Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.payload_.Destroy();
  _impl_.error_msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:petnet.simple.v1.Response)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.payload_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.error_msg_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.success_ = false;
  _impl_.error_code_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Response::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 43, 2> Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Response, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Response_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string error_msg = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(Response, _impl_.error_msg_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Response, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Response, _impl_.success_)}},
    // optional bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Response, _impl_.payload_)}},
    // optional int32 error_code = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Response, _impl_.error_code_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Response, _impl_.error_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.success_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // optional bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 error_code = 3;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.error_code_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string error_msg = 4;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.error_msg_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\0\0\11\0\0\0"
    "petnet.simple.v1.Response"
    "error_msg"
  }},
};

::uint8_t* Response::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:petnet.simple.v1.Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional bytes payload = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_payload();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional int32 error_code = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_error_code(), target);
  }

  // optional string error_msg = 4;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_error_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "petnet.simple.v1.Response.error_msg");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:petnet.simple.v1.Response)
  return target;
}

::size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:petnet.simple.v1.Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional bytes payload = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_payload());
    }

    // optional string error_msg = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_error_msg());
    }

  }
  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  // optional int32 error_code = 3;
  if (cached_has_bits & 0x00000004u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Response::_class_data_ = {
    Response::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Response::GetClassData() const {
  return &_class_data_;
}

void Response::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Response*>(&to_msg);
  auto& from = static_cast<const Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:petnet.simple.v1.Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_payload(from._internal_payload());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_error_msg(from._internal_error_msg());
    }
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (cached_has_bits & 0x00000004u) {
    _this->_internal_set_error_code(from._internal_error_code());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:petnet.simple.v1.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Response::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Response::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Response::InternalSwap(Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_msg_, &other->_impl_.error_msg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Response, _impl_.error_code_)
      + sizeof(Response::_impl_.error_code_)
      - PROTOBUF_FIELD_OFFSET(Response, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::google::protobuf::Metadata Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simple_2eproto_getter, &descriptor_table_simple_2eproto_once,
      file_level_metadata_simple_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace simple
}  // namespace petnet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
